sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.13"
before_install:
  - rvm use 2.2.2 --install --fuzzy
  - bundle install
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.13"
